### PR TITLE
Adds armv7l as wheel target

### PR DESCRIPTION
**Pull request by FL550**
This would allow users on a Raspberry to use this package

### CODE REVIEW

**Comment by michalc** [comment]
Ah... so there might be a problem. From https://github.com/uktrade/stream-unzip/actions/runs/11813910995/job/32911948492 
> rustup: installer for platform 'armv7-unknown-linux-musleabihf' not found, this may be unsupported

**Comment by FL550** [comment]
Unfortunately yes. It seems as armv7 is not a valid target for Rust at the moment. I'll have a bit more time next week and will try to find a solution. 

Why are you using Rust within the package and not staying completely Python?

**Comment by michalc** [comment]
Ah in the meantime you can probably pin to an earlier version of stream-unzip, I think [v0.0.95](https://github.com/uktrade/stream-unzip/releases/tag/v0.0.95) is Rust-free

It was to speed up ZipCrypto decrypting - it was pretty slow, and was thinking that we got to the limit with a pure Python solution, and Rust seemed as good as anything to speed it up, and at least I wasn't aware you couldn't compile Rust on armv7. There does now seem to be a downside to using Rust, so moving to a Cython solution like stream-inflate might be good?

**Comment by FL550** [comment]
Ah I see. For the moment I'll pin the version, however it should be possible to do cross compilation for armv7. I don't think a rewrite is necessary. I'll try to find a solution and create a PR then.

**Comment by michalc** [comment]
Ah: I think now fixed in v0.0.98 via

https://github.com/uktrade/stream-unzip/pull/115
https://github.com/uktrade/stream-unzip/pull/116

**Comment by FL550** [comment]
Very nice! Thanks for implementing this!

**Pull request merged**
