### PR TITLE
report crc32-checksum for every unzipped file

### PR DESCRIPTION
**Pull request by RogerJohnSenacor**
usage then is
	for file_name, file_size, unzipped_chunks, crc_32 in stream_unzip(...):

### CODE REVIEW

**Comment by michalc** [comment]
@RogerJohnSenacor Thanks for the PR

Although can I ask, what's the use case for exposing the CRC32?

**Comment by RogerJohnSenacor** [comment]
Hi!
I was in the situation to unpack large zips stored on aws s3 with a lambda, and the put of the unzipped file back to s3 can not be streamed unless you give some checksum (else it wants to read the data again to calculate md5, which was not an option). As the crc32 falls out of the zip at the beginning, this was a low hanging fruit. But unfortunately, it turns out, that, unless the s3 bucket is public, the put request has to be signed, which also requires reading the unzipped file again. So i resorted to multipart upload, where i don't need the crc32 anymore. But it might be useful for others.

**Comment by RogerJohnSenacor** [comment]
Btw. the large zips i mentioned were multipart, and to successfully supply these to stream-unzip, i had to cut away the first four bytes (PK\x07\x08). Seems to be a multipart header, after that the normal header appears (PK\x03\x04).

**Comment by michalc** [comment]
Ah thanks for the multipart zip info - have to admit I don't know anything about such zips. Good to know that, albeit with a bit of tinkering, stream-unzip can be used for those.

On the crc32 change... I think since we don't have a known use case, I'm going to have to be fairly ruthless and not accept the change. For example: for AES encrypted zip files (or at least some of them) the zip crc32 field is not populated with a real crc32 value. And so we get into complications - what do we expose in the API in those cases. To make it "always" work (which I think we should unless we have a good reason), we would in fact have to calculate the crc32 when we otherwise wouldn't. So this would have performance and complexity implications. Without solving a known problem, I unfortunately don't think it would be worth it.

**Pull request closed without merging**
